DECLARE
EID NUMBER(10);
ENAME VARCHAR(200);
EMAIL VARCHAR2(100);
WORK_TYPE VARCHAR2(100);
GENDER VARCHAR2(10);
SALARY NUMBER(10);
CONTACT NUMBER(12);
PROCEDURE INSERT_DATA_IN_EMPLOYEES
AS
BEGIN
ENAME:=:ENAME;
EMAIL:=:EMAIL;
WORK_TYPE:=:WORK_TYPE;
GENDER:=:GENDER;
SALARY:=:SALARY;
CONTACT:=:CONTACT;
SELECT COUNT(*) INTO EID FROM EMPLOYEES;
EID:=1000+EID+1;
INSERT INTO EMPLOYEES VALUES(EID,ENAME,EMAIL,WORK_TYPE,GENDER,SALARY,CONTACT);
END;
BEGIN
INSERT_DATA_IN_EMPLOYEES();
END;
