DECLARE
IID NUMBER(10);
INAME VARCHAR(200);
PURCHASED DATE;
QTY NUMBER(10);
PROCEDURE INSERT_DATA_IN_INGREDIENTS
AS
BEGIN
INAME:=:INAME;
PURCHASED:=:PURCHASED;
QTY:=:QTY;
SELECT COUNT(*) INTO IID FROM INGREDIENTS;
IID:=2000+IID+1;
INSERT INTO INGREDIENTS VALUES(IID,INAME,QTY,PURCHASED);
END;
BEGIN
INSERT_DATA_IN_INGREDIENTS();
END;
