DECLARE
BONUS NUMBER;
COUT NUMBER;
EMPLOYEE NUMBER;
CURSOR BON IS SELECT EMP_ID,SALARY FROM EMPLOYEES WHERE TYPE_OF_WORK='WAITER';
EID EMPLOYEES.EMP_ID%TYPE;
SAL EMPLOYEES.SALARY%TYPE;
BEGIN
BONUS:=:BONUS;
COUT:=:COUT;
DBMS_OUTPUT.PUT_LINE('SALARIES TO BE DISTRIBUTED TO THE BELOW MENTIONED');
DBMS_OUTPUT.PUT_LINE('ID      SALARY     COUNT');
OPEN BON;
LOOP
FETCH BON INTO EID,SAL;
EXIT WHEN (BON%NOTFOUND);
SELECT COUNT(*) INTO EMPLOYEE FROM ORDER_TABLE WHERE HANDLED_BY=EID;
IF (EMPLOYEE>=COUT) THEN
	SAL:=SAL+BONUS;
	DBMS_OUTPUT.PUT_LINE(EID||'    '||SAL||'     '||EMPLOYEE);
END IF;
COMMIT;
END LOOP;
CLOSE BON;
END;
