DECLARE
BONUS NUMBER;
CURSOR SALS IS SELECT SALARY,EMP_ID FROM EMPLOYEES;
SAL EMPLOYEES.SALARY%TYPE;
EID EMPLOYEES.EMP_ID%TYPE;
BEGIN
BONUS:=:BONUS;
DBMS_OUTPUT.PUT_LINE('SALARIES TO BE DISTRIBUTED');
DBMS_OUTPUT.PUT_LINE('ID      SALARY');
OPEN SALS;
LOOP
FETCH SALS INTO SAL,EID;
EXIT WHEN (SALS%NOTFOUND);
SAL:=SAL+BONUS;
DBMS_OUTPUT.PUT_LINE(EID||'    '||SAL);
COMMIT;
END LOOP;
CLOSE SALS;
END;
