DECLARE
SALES_ON DATE;
tAMOUNT NUMBER(10):=0;
CURSOR DATES IS SELECT ODATE,AMOUNT FROM ORDER_TABLE;
DAT ORDER_TABLE.ODATE%TYPE;
PRICE ORDER_TABLE.AMOUNT%TYPE;
BEGIN
SALES_ON:=:SALES_ON;
OPEN DATES;
LOOP
FETCH DATES INTO DAT,PRICE;
EXIT WHEN (DATES%NOTFOUND);
IF (SALES_ON=DAT) THEN
TAMOUNT:=TAMOUNT+PRICE;
END IF;
COMMIT;
END LOOP;
CLOSE DATES;
DBMS_OUTPUT.PUT_LINE('SALES ON '||SALES_ON||'IS '||TAMOUNT);
END;
