DECLARE
PURCHASED DATE;
INAME VARCHAR2(50);
QTY NUMBER(10);
BEGIN
INAME:=:INAME;
SELECT QUANTITY, LAST_PURCHASED_ON INTO QTY,PURCHASED FROM INGREDIENTS WHERE ING_NAME=INAME;
DBMS_OUTPUT.PUT_LINE(INAME||' QUANTITY: '||QTY||' LAST PURCHASED ON: '||PURCHASED);
EXCEPTION 
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('ENTRY MISSING');
END;
