DECLARE
QTY  NUMBER(10);
NAME VARCHAR2(10);
QUAN NUMBER(10);
BEGIN
NAME:=:NAME;
QTY:=:QTY;
SELECT QUANTITY INTO QUAN FROM INGREDIENTS WHERE ING_NAME=NAME;
QUAN:=QUAN-QTY;
IF (QUAN>0 )THEN
DBMS_OUTPUT.PUT_LINE('QUANTITY FETCHED. REMAINING:'||QUAN);
ELSE
DBMS_OUTPUT.PUT_LINE('INSUFFICIENT QUANTITY');
END IF;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
	DBMS_OUTPUT.PUT_LINE('MISSING ENTRY');
END;
