CREATE OR REPLACE TRIGGER display_QUANTITY_changes 
BEFORE UPDATE ON INGREDIENTS
FOR EACH ROW 
WHEN (NEW.ING_ID > 0) 
BEGIN 
   dbms_output.put_line('PREVIOUS PURCHASED DATE: ' || :OLD.LAST_PURCHASED_ON); 
   dbms_output.put_line('NEW PURCHASE DATE: ' || :NEW.LAST_PURCHASED_ON); 
END; 
