DECLARE
SEATS NUMBER(10);
VAC NUMBER(10);
CURSOR ROLESS IS SELECT DISTINCT TYPE_OF_WORK FROM EMPLOYEES;
DUTY EMPLOYEES.TYPE_OF_WORK%TYPE;
COUT NUMBER(10);
BEGIN
SEATS:=:SEATS;
DBMS_OUTPUT.PUT_LINE('ROLES        VACANCIES');
OPEN ROLESS;
LOOP
FETCH ROLESS INTO DUTY;
EXIT WHEN (ROLESS%NOTFOUND);
SELECT COUNT(*) INTO COUT FROM EMPLOYEES WHERE TYPE_OF_WORK=DUTY;
VAC:=SEATS-COUT;
DBMS_OUTPUT.PUT_LINE(DUTY||'    '||VAC);
END LOOP;
CLOSE ROLESS;
END;
